### ISSUE TITLE
Sneefer daemonset is crashing with "Mysql/wordpress" demo 

### ISSUE THREAD

**Issue by slashben** [kubescape/sneeffer#4]
Steps to reproduce
1. Install sneefer on cluster
2. Install Wordpress example app: `kubectl -n MySQL -f https://raw.githubusercontent.com/kubernetes/examples/master/mysql-wordpress-pd/mysql-deployment.yaml`
3. Sneefer crashes with the log bellow

```
2022/10/24 15:03:31 INFO: sneeffer is ready to watch over node XXX
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/kubescape/sneeffer/sneeffer/k8s_watcher.getImageID(...)
        /etc/sneeffer/sneeffer/k8s_watcher/k8sWatcher.go:114
github.com/kubescape/sneeffer/sneeffer/k8s_watcher.(*ContainerWatcher).StartWatchingOnNewContainers(0xc0007a5f40)
        /etc/sneeffer/sneeffer/k8s_watcher/k8sWatcher.go:245 +0xc05
main.main()
        /etc/sneeffer/main.go:52 +0x318
```

**Comment by slashben** [comment]
It looks like an issue that reproduces on GKE (`v1.22.12-gke.2300`)

**Comment by slashben** [comment]
Image ID looks different on different Kubernetes versions:
` imageID: docker-pullable://nginx@sha256:f7988fb6c02e0ce69257d9bd9cf37ae20a60f1df7563c3a2a6abe24160306b8d `
or 
`imageID: docker.io/library/nginx@sha256:f7988fb6c02e0ce69257d9bd9cf37ae20a60f1df7563c3a2a6abe24160306b8d`

**Comment by rcohencyberarmor** [comment]
fixed and pushed to image
